### ISSUE TITLE
Remove builtin function echo

### ISSUE THREAD

**Issue by zakuro9715** [cotowali/cotowali#44] opened 2021-11-20 00:09 UTC

**Comment by pdietl** [comment] 2022-07-23 23:59
@zakuro9715 should this be marked as a duplicate of #45 ?

**Comment by zakuro9715** [comment] 2022-07-26 03:45
This issue is cotowali's builtin function `echo()`. echo is implemented during prototype development, but no longer needed since `println` now exists.

`echo()` is implemented in the compiler and requires a bit of modification to the compiler

**Closed** 2022-07-27 08:07 UTC
Labels: zakuro: task
